# Generated by Django 3.2.9 on 2021-11-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['field'], 'verbose_name_plural': 'Metadata'},
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='schema_field',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='params',
        ),
        migrations.AddField(
            model_name='metadata',
            name='condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='format_in',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='format_out',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
