# Generated by Django 3.2.9 on 2021-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20211104_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbs',
            options={'ordering': ['code'], 'verbose_name_plural': 'CBS'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['schema_field'], 'verbose_name_plural': 'Metadata'},
        ),
        migrations.AddField(
            model_name='schemafield',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
